### ISSUE TITLE
Difference between compact and fast graph engine

### ISSUE THREAD

**Issue by VoVAllen** [alibaba/euler#10]
Hi, Thanks for your work!

I'm curious about what's the difference between compact and fast graph engine. Could you elaborate more on this? Thanks.

**Comment by zakheav** [comment]
> Hi, Thanks for your work!
> 
> I'm curious about what's the difference between compact and fast graph engine. Could you elaborate more on this? Thanks.

The main difference between these two is in the neighbor sampling part. Fast graph use alias method  which achieve O(1) sampling, while compact graph use binary search.  Compact graph consume less memory.

**Comment by yzh119** [comment]
So this being said your compact graph engine does not support sampling strategy with a dynamic distribution like adaptive sampling, is that right?

**Comment by zakheav** [comment]
> So this being said your compact graph engine does not support sampling strategy with a dynamic distribution like adaptive sampling, is that right?

Yes.

**Comment by VoVAllen** [comment]
Thanks!
