### ISSUE TITLE
有关fast_node.cc里的问题

### ISSUE THREAD

**Issue by marvelousgirl** [alibaba/euler#123]
为什么fast_node.cc里的 edge_group_collection_ 是CompactWeightedCollection, 而不是 FastWeightedCollection?

**Comment by zakheav** [comment]
因为这个edge group collection的size很小，log(n)时间复杂度就足够了，没必要去构建alias-table这种O(1)时间复杂度的采样器

**Comment by marvelousgirl** [comment]
@请问有关alias method的介绍去哪里看
