### ISSUE TITLE
lshne的实现和wiki的介绍不太一致

### ISSUE THREAD

**Issue by yaochitc** [alibaba/euler#126]
看wiki里的介绍，会训练p×q+p个dnn，分别对应的是source和target的encoding，但是实际代码里成了2×view_num个dnn，这里是进行了简化吗？

**Comment by YanZhangN** [comment]
可以参考以下代码https://github.com/alibaba/euler/blob/ff40594cfebfa55ada4a1142acbc020dab368d81/tf_euler/python/models/lshne.py#L125
https://github.com/alibaba/euler/blob/ff40594cfebfa55ada4a1142acbc020dab368d81/tf_euler/python/models/lshne.py#L71
self.out_layer中是lshne的dnn，对于src节点来说需要 p (node_type) * q (view_num)个dnn，对于 tar节点需要 p(node_type)个dnn。加起来就是p*q+p个。

**Comment by yaochitc** [comment]
好像有点懂了，之前以为这里的p是和view_num一样的超参，多谢回复。

**Comment by marvelousgirl** [comment]
您好，请问跑通lshne这个模型了吗？
