### ISSUE TITLE
关于测试集中正负样本的个数

### ISSUE THREAD

**Issue by xiaojingli** [alibaba/euler#13]
首先感谢开源这么好的仓库！
因为我的数据中还没有节点的特征，所以就将 `float_feature`的第0维设成了[0]和[1]这样的一维二分类特征，将`float_feature`的第1维设置成了[1].也就是
```
buf["float_feature"][0] = [class_map[node]]
buf["float_feature"][1] = [1]
```
边只有类别信息没有特征信息。

生成的`data.json`文件为：
```
{"node_weight": 1, "uint64_feature": {}, "float_feature": {"0": [1], "1": [1]}, "edge": [{"src_id": 0, "weight": 1, "uint64_feature": {}, "float_feature": {}, "dst_id": 1210723, "edge_type": 0, "binary_feature": {}}, {"src_id": 0, "weight": 1, "uint64_feature": {}, "float_feature": {}, "dst_id": 979074, "edge_type": 0, "binary_feature": {}}
```
但是在打印结果(tp,fp,fn,tp)的时候发现这四个值的总和并不等于test_id中的个数，而且tp的总数远多于test_id中应该为正样本的个数。想请问：1. 总数不匹配的问题是由于采样引起的吗？2. 已排除class_map文件出错的可能性，但是tp值比label为1的数据多出来很多 3. 对于二分类的问题是否因该将标签赋值为[0],[1]，还是有其他标注方法呢？

**Comment by YanZhangN** [comment]
你的tp fp tn fn是以怎样的方式计算的？给一下你的代码吧。

**Comment by yangsiran** [comment]
> 你的tp fp tn fn是以怎样的方式计算的？给一下你的代码吧。

『在打印结果(tp,fp,fn,tp)的时候发现这四个值的总和并不等于test_id中的个数』这个是比较奇怪的，感觉和数据没有太大关系。理论上tp fp tn fn的总和应该等于总id的个数。

**Comment by xiaojingli** [comment]
谢谢二位的回复！
> > 你的tp fp tn fn是以怎样的方式计算的？给一下你的代码吧。
> 
> 『在打印结果(tp,fp,fn,tp)的时候发现这四个值的总和并不等于test_id中的个数』这个是比较奇怪的，感觉和数据没有太大关系。理论上tp fp tn fn的总和应该等于总id的个数。

我是直接在`metrics.py`中添加了一个函数，使`model(source)`在`run_evaluation`的时候也会返回(fn,fp,fn,tp)的值，代码和计算f1分数时一样：
```   python
_, tp = tf.metrics.true_positives(labels, predictions)
_, fn = tf.metrics.false_negatives(labels, predictions)
_, fp = tf.metrics.false_positives(labels, predictions)
_, tn = tf.metrics.true_negatives(labels, predictions)
```

**Comment by yangsiran** [comment]
@xiaojingli 这个代码的运行后，四个值的和应该是test id的个数 x num_class (2)。你的这四个值和test id的个数分别是多少？

**Comment by yangsiran** [comment]
@xiaojingli 文档里面的使用指南有[一处错误](https://github.com/alibaba/euler/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/_compare/d5e7a6d04c53f47e89f07d30b2b8ec7d35b73ed1...f02390d68056314de6bd742194fa659ab37fc1a9)，`--num_class`选项应该为`--num_classes`。所以你的运行命令应该修改为：
```
python -m tf_euler   
--data_dir data  --id_file data/mergedv2_test.id   --max_id 3167911 
--feature_idx 1 --feature_dim 1 
--label_idx 0 --label_dim 1 --num_classes 2  
--model graphsage_supervised --mode evaluate
```
另外，*data/mergedv2_test.id*这个文件的期望格式应该是一个id一行的，不知道你的文件是不是这样的。

**Comment by xiaojingli** [comment]
@yangsiran 谢谢！`--num_classes`已改，但是输出成了`(2294，778，778，2294)`...样本提取好像还是有问题？
查了一下test_id的文件格式是对的哈

**Comment by yangsiran** [comment]
@xiaojingli 看起来样本格式和运行的参数都没有什么问题。从结果来看像是test_id文件中有3073个id。麻烦提供一个能复现问题的经裁剪最小的图数据文件和最小的test_id文件。（图关系对这个问题应该不是很重要）

**Comment by xiaojingli** [comment]
@yangsiran 我重新写了一下输出(tp,fn,fp,tn)的代码，现在在metrics.py中将f1_score的函数重写成
```python
def f1_score(labels, predictions, name=None):
  """Streaming f1 score.
  """
  with tf.variable_scope(name, 'f1', (labels, predictions)):
    epsilon = 1e-7
    _, tp = tf.metrics.true_positives(labels, predictions)
    _, fn = tf.metrics.false_negatives(labels, predictions)
    _, fp = tf.metrics.false_positives(labels, predictions)
    _, tn = tf.metrics.true_negatives(labels, predictions)
    precision = tf.div(tp, epsilon + tp + fp, name='precision')
    recall = tf.div(tp, epsilon + tp + fn, name='recall')
    f1 = 2.0 * precision * recall / (precision + recall + epsilon)
  return (f1,tp,fn,fp,tn)
```
现在打印出来的值为`(0.7640961, 6708.0, 2072.0, 2070.0, 6710.0)` ，这个数据好像还是不符合真实的数据分布`（2681，6099）`？

**Comment by yangsiran** [comment]
参考这段实现：
https://github.com/alibaba/euler/blob/46ca9c5e3bfd0b29343b13d0e231f32563c57b47/tf_euler/python/models/base.py#L224-L232
假设test数据的label分布是1 -> 2681，0 -> 6099。那么监督模型中labels为2681个(0, 1)和6099个(1, 0)。
当predictions全为(0, 1)时，(tp, fn, fp, tn)为(2681, 6099, 6099, 2681)。但实际上由于模型的权重和数据分布（在GraphSage和全1特征的条件下就是顶点是否有邻居）preditions的结果未必如此。

**Comment by YanZhangN** [comment]
实际上，tf.metric.true_positives 这几个方法是element-wise的，而不是row-wise的，以tp为例，tp等于|{(x,y)| labels[x,y]==1 && predictions[x,y]==1}| (即labels和predictions对应位置上同时为1的个数)，因此在labels的shape为[#node,2]时，假设labels一定是one_hot的，那么tp的最大值是#node。以 @yangsiran 上面举的例子，如果predictions全为(1,0)时，那么tp就是6099，因此想要实现你提问中的tp<真实1，label和prediction可以直接采用[#node]作为shape，负样本用0，正样本用1即可

**Comment by xiaojingli** [comment]
@YanZhangN @yangsiran 非常感谢两位的解答！
