### ISSUE TITLE
evaluate和save_embedding的时候，输出的embedding结果存在部分节点全0的现象

### ISSUE THREAD

**Issue by uhuanli** [alibaba/euler#131]
首先确认分片是按照wiki的x = nodeID%partNum进行的，而且存储在part_x上哈

问题：evaluate和save_embedding的时候，输出的embedding结果存在部分节点全0的现象，而且多次调用发现，这种0的现象不稳定（同一个节点，上次调用全0，下次有值）；
从代码上猜测，可能是get_dense_feature的时候，通信结果没返回，导致使用了初始化的结果（全0）

结果：
1. evaluate：结果存在偏差；
2. save_embedding：结果不完全可用；
3. train：是否有影响？如果当前节点标签是1，用get_dense_feature操作拉取的时候，label拉取正常，特征拉取异常（全0），则预测输出为0，产生loss，影响dense_layer的bias参数，进而在后续迭代中会影响所有的参数

**Comment by uhuanli** [comment]
另外想问下，通信延迟30ms左右的情况下，是否会返回全0？ get_dense_feature对应callback哪里可以设置timeout？

**Comment by yangsiran** [comment]
没遇到这种情况，请问您打印了get_dense_feature然后发现不稳定吗？

**Comment by uhuanli** [comment]
> 没遇到这种情况，请问您打印了get_dense_feature的结果然后发现不稳定吗？

发现是我预处理的时候，存在部分孤立点，然后在建立邻接表的时候，这部分孤立点删了。。。
多有打扰，非常感谢
