### ISSUE TITLE
关于边的负采样

### ISSUE THREAD

**Issue by Piento28** [alibaba/euler#133]
查看源码后，我的理解是在给定比如邻居聚合类方法需要encoder的目标点后，随意采样一些点和目标点相连作为负采样。这算是准负采样？利用大多数的图具有稀疏性？

如果要自己重写边的负采样，请问是需要自己写C++代码吗？具体该如何操作呢？

**Comment by yangsiran** [comment]
可以尝试在TensorFlow代码里面把负采样结果里面属于目标点邻居的过滤掉？

**Comment by YanZhangN** [comment]
用get_full_neighbor接口拿到source节点的全部邻居。然后对sample_node产生的候选负例节点进行过滤即可。

**Comment by lixusign** [comment]
> 可以尝试在TensorFlow代码里面把负采样结果里面属于目标点邻居的过滤掉？

@yangsiran 貌似说反了，YanZhangN 说的是对的
