### ISSUE TITLE
数据格式设计的考虑

### ISSUE THREAD

**Issue by mandyzore** [alibaba/euler#140]
Euler里图的存储格式是，对于每个节点，为什么既要存储它的neighbor邻居节点列表，又要存储它的edge出边列表？这样不冗余么，是否只存出边列表就够了呢？请教一下这么设计是出于怎样的考虑。

**Comment by zakheav** [comment]
neigbor列表是为了对邻居进行带权采样，是一个邻居采样器

**Comment by mandyzore** [comment]
哦这样
