### ISSUE TITLE
想问下阿里在测试中，网卡会成为性能瓶颈吗？麻烦告知下带宽

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#142]
如题，在100万+qps下，图节点的out带宽

**Comment by zakheav** [comment]
如果单台机器部署euler，很多worker去请求服务，是有可能带宽瓶颈的。




| |
计算机院 魏源
邮箱：18810543471@163.com
|

签名由 网易邮箱大师 定制

在2019年08月12日 19:53，lixusign 写道：

如题

**Comment by lixusign** [comment]
我现在是是10个shard，10个euler节点，30个tf-worker，2.5亿节点，8亿边，跑hne， 发现万兆网卡打满了。

**Comment by alinamimi** [comment]
对于每个batch请求的节点，目前没有unique操作，会导致各个服务器的负载不太平衡。可以在worker端进行unique操作，可以解决这个问题
