### ISSUE TITLE
关于GPU多卡的利用

### ISSUE THREAD

**Issue by wenruij** [alibaba/euler#154]
之前的Issues作者有提到：
“而其他的op以及图op和模型训练的交互仍然是走的TensorFlow的逻辑”

“而我们的euler相关的op都是基于cpu编写的，多卡支持实际上和Euler本身没有太大关系”

那么如果想要支持，单机多GPU卡，或者 多机多GPU卡，需要我们自己去支持吗？比如我们使用euler时自己去封装如下api:

[tf.estimator.train_and_evaluate](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate)  or

[tf.train.SyncReplicasOptimizer](https://www.tensorflow.org/api_docs/python/tf/train/SyncReplicasOptimizer)

还是说，euler已经封装了类似于这些的api，所以天然就支持 单机多GPU卡，或者 多机多GPU卡？

**Comment by alinamimi** [comment]
你可以把Euler理解为一种dataset，所以GPU对于Euler没有什么加速作用，模型训练都在tf端，如果想用GPU，按照tf的方法使用GPU就ok

**Comment by wenruij** [comment]
谢谢解答

**Comment by lixusign** [comment]
但是，euler的IO消耗会，导致GPU训练速度也提不上来，因为不在本地内存
