### ISSUE TITLE
邻居采样与预期结果不符？

### ISSUE THREAD

**Issue by CaoYang17621** [alibaba/euler#156]
以“数据准备”部分的手机数据作为测试数据，运行“邻居采样”和“获取所有邻居”

![image](https://user-images.githubusercontent.com/31542284/65305397-ab3d5e00-dbb5-11e9-9fbf-adad74b21b48.png)
可以看到：
1. sample_neighbor 没有采样到节点
2. 然而get_full_neightbor显示，node_1通过rela_1指向了node_2
所以sample_neighbor应该能采样到node_2才对，为何没有采样到呢？

以及，get_sparse_feature中参数 default_values 失效

**Comment by CaoYang17621** [comment]
问题2：sample_fanout函数，返回的边类型列表是权重 而非边类型
![image](https://user-images.githubusercontent.com/31542284/65307556-9adbb200-dbba-11e9-8e93-bd31969cc05f.png)

**Comment by alinamimi** [comment]
第二个问题是我们的bug，已经fix了

**Comment by CaoYang17621** [comment]
问题1已经解决了：
之前是使用pip install euler-gl安装，发布包并不是最新的代码
使用git源码编译安装 则无问题1
