### ISSUE TITLE
label获取: get_label_from_node_feature VS get_label_from_edge_feature

### ISSUE THREAD

**Issue by wenruij** [alibaba/euler#162]
关于label的获取，参数中的 `-—label_idx`  和 `--label_dim` 是从 node_feature中去获取，那么有办法从edge_feature中去获取吗？

主要是考虑到如下这样的社交场景：

二分图：左侧是作者发布的内容：feeds ，右侧是用户：users
user对feed的click(或者share, like, buy等等其他行为)构成一条边，同时也是正样本，这种label的信息通常和edge绑定在一起，那么这种情况 如何用 graphsage_supervised 去训练呢？

**Comment by zakheav** [comment]
可以把edge 的label信息放到edge的dense feature里面，用 https://github.com/alibaba/euler/wiki/Euler-OP 里面介绍的tf_euler.get_edge_dense_feature来做

**Comment by wenruij** [comment]
多谢解答，这个感觉可以加一个参数，告诉模型 是从node_feature获取label还是edge_feature中获取
