### ISSUE TITLE
Question about the the role of ZK in Euler

### ISSUE THREAD

**Issue by AtekiRyu** [alibaba/euler#163]
Thanks for the excellent project!
I have a question about ZK, 

- It seems that you didn't use it for GraphEngile failover/replica, just uses it as a naming service to make client can get the GraphEngine Server address.  Is my understanding correct ?  
- Or it depends on the parameter, there will be multiple replicas when worker_num > shard_num? 

Thanks in advance~

**Comment by yangsiran** [comment]
The second point is correct. There will be multiple replicas when worker_num > shard_num. But this is not in the default run loop.

**Comment by AtekiRyu** [comment]
thanks your explanation!
