### ISSUE TITLE
sparse  embedding是不是对于feature dim 多加了一次1？

### ISSUE THREAD

**Issue by wentixiaogege** [alibaba/euler#164]
#####首先
class SparseSageEncoder(SageEncoder):
  """
  """

  @staticmethod
  def create_sparse_embeddings(feature_dims):
    sparse_embeddings = [
        **layers.SparseEmbedding(feature_dim + 1, 16)**
        for feature_dim in feature_dims
    ]
    return sparse_embeddings

#####其次
class Embedding(Layer):
  """
  Id to dense vector embedding.
  """

  def __init__(self,
               max_id,
               dim,
               initializer=lambda: tf.truncated_normal_initializer(stddev=0.1),
               **kwargs):
    super(Embedding, self).__init__(**kwargs)
    self.max_id = max_id
    self.dim = dim
    self.initializer = initializer

  def build(self, input_shape):
    self.embeddings = tf.get_variable(
        'embeddings',
        **shape=[self.max_id + 1, self.dim],**
        initializer=self.initializer())
    self.built = True

请及时确认一下

**Comment by zakheav** [comment]
这个feature dim实际上指的是feature的max id，+1是为了default的embedding

**Comment by wentixiaogege** [comment]
是的，但是sparceEmbedding和正常的embedding都加了一个1；？？最后maxid 9 ；应该是10维度的输出，现在11维度，如何去匹配呢？default是从0开始的，还是最大的呢?

**Comment by alinamimi** [comment]
是的，多加了一次，这个应该是一个bug，default默认是maxid + 1

**Comment by wentixiaogege** [comment]
嗯嗯，麻烦确认一下，我提取feature特征的方式对不对，我本地修改了这个bug了。多谢啦

**Comment by wentixiaogege** [comment]
https://github.com/alibaba/euler/issues/159

**Comment by alinamimi** [comment]
对的

**Comment by wentixiaogege** [comment]
好的多谢啦~　其实我已经在用了哈哈，是否需要我改后的提交到咱们这个上面呢？还是你们自己改就行了哈

**Comment by alinamimi** [comment]
你提交吧，我们merge

**Comment by wentixiaogege** [comment]
好的～
