### ISSUE TITLE
OK.

### ISSUE THREAD

**Issue by TheDragonLord1939** [alibaba/euler#165]

**Comment by zakheav** [comment]
你的数据存储在hdfs上吧？估计得通过源码编译安装euler

**Comment by TheDragonLord1939** [comment]
> 你的数据存储在hdfs上吧？估计得通过源码编译安装euler

是的，官网那个分布式计算样例数据说需要放到hdfs上，--data_dir hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi， 但是卡住不出结果，错误日志见上面。  E1017 03:55:42.619585 7732 graph_engine.cc:75] no hdfs file io factory register。  不知是什么原因导致的。

**Comment by zakheav** [comment]
就是需要源码安装，直接pip安装的那个是为了单机用户准备的，所以没有编译hdfs的部分。详情可以看euler编译安装那部分

**Comment by TheDragonLord1939** [comment]
> 就是需要源码安装，直接pip安装的那个是为了单机用户准备的，所以没有编译hdfs的部分。详情可以看euler编译安装那部分

好的，我试试。

**Comment by TheDragonLord1939** [comment]
> 就是需要源码安装，直接pip安装的那个是为了单机用户准备的，所以没有编译hdfs的部分。详情可以看euler编译安装那部分

 你好，执行 make -j 32时，执行到40%左右，报错，错误如下：
===============================================================================
[ 40%] Performing build step for 'jemalloc'
cp include/jemalloc/internal/private_namespace.gen.h include/jemalloc/internal/private_namespace.gen.h
[ 40%] Performing install step for 'jemalloc'
Skipping install step.
[ 40%] Completed 'jemalloc'
[ 40%] Built target jemalloc
make: *** [all] Error 2

**Comment by TheDragonLord1939** [comment]
> 把完整的报错发一下吧，可能是上面某个地方报错了。

重新执行后OK了。  现在在运行官网提供的分布式计算样例，执行脚本如下
sh /opt/euler/dist_tf_euler.sh
--data_dir hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi
--euler_zk_addr ip-172-40-48-247.ec2.internal:2181
--euler_zk_path /euler
--max_id 56944 --feature_idx 1 --feature_dim 50 --label_idx 0 --label_dim 121
--model graphsage_supervised --mode train
遇到了如下错误。
[root@ip-172-40-48-247 /tmp]# cat log.worker.0
hdfs file io factory register
local file io factory register
hdfs file io factory register
local file io factory register
2019-10-17 08:34:39.784921: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-17 08:34:39.793504: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job ps -> {0 -> localhost:1998, 1 -> localhost:1999}
2019-10-17 08:34:39.793527: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job worker -> {0 -> localhost:2000, 1 -> localhost:2001}
2019-10-17 08:34:39.794187: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:381] Started server with target: grpc://localhost:2000
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1017 08:34:39.824100 19900 remote_graph.cc:91] Initialize RemoteGraph, connect to server monitor: [ip-172-40-48-247.ec2.internal:2181, /euler]
2019-10-17 08:34:42,485 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2019-10-17 08:34:42,486 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2019-10-17 08:34:42,485 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2019-10-17 08:34:42,485 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1017 08:34:42.744551 20102 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi_train.id data error!
E1017 08:34:43.289228 20100 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi-id_map.json data error!
E1017 08:34:44.134630 20099 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi-G.json data error!
2019-10-17 08:34:44,446 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2019-10-17 08:34:44,731 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
E1017 08:34:44.917265 20101 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi_data.json data error!
I1017 08:34:44.917500 20021 graph_builder.cc:127] Each Thread Load Finish! Node Count:0 Edge Count:0
E1017 08:34:44.917518 20021 graph_builder.cc:131] Graph build failed!
I1017 08:34:44.917531 20021 graph_service.cc:179] service init finish
E1017 08:34:44.917538 20021 graph_service.cc:157] service error

数据我是直接put到hdfs是上的。是还需要什么转化么？

**Comment by TheDragonLord1939** [comment]
> E1017 08:34:42.744551 20102 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi_train.id data error!
> E1017 08:34:43.289228 20100 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi-id_map.json data error!
> E1017 08:34:44.134630 20099 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi-G.json data error!
> 2019-10-17 08:34:44,446 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
> 2019-10-17 08:34:44,731 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
> E1017 08:34:44.917265 20101 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi_data.json data error!

提示hdfs上的数据不正确。
E1017 08:34:42.744551 20102 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi_train.id data error!
E1017 08:34:43.289228 20100 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi-id_map.json data error!
E1017 08:34:44.134630 20099 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi-G.json data error!
2019-10-17 08:34:44,446 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2019-10-17 08:34:44,731 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
E1017 08:34:44.917265 20101 graph_builder.cc:75] hdfs://ip-172-40-58-121.ec2.internal:9000/euler/ppi/ppi_data.json data error!

**Comment by zakheav** [comment]
参考 https://github.com/alibaba/euler/wiki/%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87 里面的数据准备

**Comment by TheDragonLord1939** [comment]
> 参考 https://github.com/alibaba/euler/wiki/%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87 里面的数据准备
好的。 我问下，  官网不是提供了一个数据么，脚本如下。
apt-get update && apt-get install -y curl
curl -k -O https://raw.githubusercontent.com/alibaba/euler/master/examples/ppi_data.py
pip install networkx==1.11 sklearn
python ppi_data.py

我单机执行计算这个数据可以使用。   我将这个数据put到hdfs上，进行分布式计算，然后报出上面的错误。  也就是说这个官网的demo中的数据，分布式计算不能使用对吧？

**Comment by zakheav** [comment]
对，需要转化成二进制数据推到hdfs上

**Comment by TheDragonLord1939** [comment]
> > 对，需要转化成二进制数据推到hdfs上
> 
> 你好，需要转化成二进制数据推到hdfs上，这个操作有脚本么？

我想把这个官网提供的例子，在分布式计算下跑通，麻烦指点下，这个二进制如何转换？  有转化的python或java代码么，我参考下，感谢。

**Comment by TheDragonLord1939** [comment]
> > > 对，需要转化成二进制数据推到hdfs上
> > 
> > 
> > 你好，需要转化成二进制数据推到hdfs上，这个操作有脚本么？
> 
> 我想把这个官网提供的例子，在分布式计算下跑通，麻烦指点下，这个二进制如何转换？ 有转化的python或java代码么，我参考下，感谢。

[root@ip-172-40-48-247 /opt/euler/ppi]# ll
total 608800
-rw-r--r-- 1 root root  21285946 Oct 17 07:08 ppi-class_map.json
-rw-r--r-- 1 root root 126663984 Oct 17 07:09 ppi_data.dat
-rw-r--r-- 1 root root 319294727 Oct 17 07:08 ppi_data.json
-rw-r--r-- 1 root root  22777680 Oct 17 07:08 ppi-feats.npy
-rw-r--r-- 1 root root  31684076 Oct 17 07:08 ppi-G.json
-rw-r--r-- 1 root root    888884 Oct 17 07:08 ppi-id_map.json
-rw-r--r-- 1 root root       218 Oct 17 07:08 ppi_meta.json
-rw-r--r-- 1 root root     33144 Oct 17 07:08 ppi_test.id
-rw-r--r-- 1 root root    258326 Oct 17 07:08 ppi_train.id
-rw-r--r-- 1 root root     39084 Oct 17 07:08 ppi_val.id
-rw-r--r-- 1 root root 100459319 Oct 17 07:08 ppi-walks.txt

整个目录/ppi 直接转成二进制么？

**Comment by zakheav** [comment]
请仔细看看我刚才发你的文档，应该就知道怎么搞了

**Comment by TheDragonLord1939** [comment]
> 请仔细看看我刚才发你的文档，应该就知道怎么搞了

好的，感谢。
