### ISSUE TITLE
base_layers中call方法的输入是什么形式

### ISSUE THREAD

**Issue by Ljl-Jdsk** [alibaba/euler#171]
感谢开源这么好的框架！
我是直接从顶层看的代码，base_layers里几个类的call方法的输入是一个batch的顶点id吗？
具体是只有顶点id的格式，比如[0, 1, 2, 3, 4, 5, ..., batch_size-1]，还是像json格式一样的block，
或是是其它格式，可以给举个例子吗？
谢谢，祝好！

**Comment by zakheav** [comment]
就是batch顶点的id，一个tensorflow的 1-D tensor
