### ISSUE TITLE
tf_euler/python/base_layers中的SparseEmbedding(Embedding)主要是应用在什么场景呀

### ISSUE THREAD

**Issue by Ljl-Jdsk** [alibaba/euler#183]
您好，SparseEmbedding中
tf.nn.embedding_lookup_sparse(self.embeddings, inputs, None, self.combiner)
参数embedding是全部id的embedding矩阵吗，inputs这个稀疏张量在什么场景下用到呀，
权重都是1，inputs里面会出现一些相同的id吧，比如id_1 出现了两次，返回的就是id_1embedding的两倍，没想出来什么场景会出现这样的情况？请指教！
非常感谢！

**Comment by alinamimi** [comment]
SparseEmbedding 一般应用在id类的embedding，比如nodeid，featureid

**Comment by zakheav** [comment]
比如用到了节点的id特征，我们事先把每个节点id都初始化分配一个随机的embedding，SparseEmbedding就是用节点的id去参数矩阵上查询对应节点的embedding。

**Comment by Ljl-Jdsk** [comment]
这种用tf.nn.embedding_lookup就可以啦，请问为什么要用tf.nn.embedding_lookup_sparse呢？

**Comment by zakheav** [comment]
如果在sparse feature的情况下，比如有一路feature是query的分词结果，每个sparse id是每个词的id，这一路feature的feature value是不定长的；使用tf.nn.embedding_lookup_sparse可以把每个词id的embedding查回来，然后按照指定的aggr方法比如mean，add等将这一路sparse feature融合成一个embedding

**Comment by Ljl-Jdsk** [comment]
哦哦，明白了，是用具体的query分词后，用来训练词/字符级的embedding吗？
（就像比如学生甲的爱好是篮球，游泳；学生乙的爱好是编程；学生丙爱好是游戏；学生丁无爱好。
我想根据学生的爱好来训练 “篮球”、“游泳”、“编程”的embedding，因为每一个学生的爱好数量是不一定的，矩阵非常非常稀疏，所以用sparse embedding来训练吧！）
一般稀疏矩阵的长度是根据经验来确定的，太长的就截断，还是直接取最大长度呢？学生党没什么业务经验。

**Comment by zakheav** [comment]
存放embedding的参数矩阵大小和id的最大值有关

**Comment by Ljl-Jdsk** [comment]
您好，我是想问，sp_ids是一个SparseTensor，里面是要传dense_shape的，假如一个query非常长，由20个词组成，而一般的query不会超过5个词，这时候SparseTensor的dense_shape是batch_size*50, 还是batch_size*5，这样实际上是将50个词的id截断只取了前5个。

**Comment by zakheav** [comment]
用最长的那个@Ljl-Jdsk

**Comment by Ljl-Jdsk** [comment]
@zakheav 请问大神：所以在具体的业务场景里，无论是最大query是50还是500，用了SparseTensor后，即使 dense_shape=[batch_size, 500], 对其它query的查表，计算速度是没有影响的吗？
如果用tf.sparse_tensor_to_dense将sparseTensor转成tensor形式，是严格按照
真实id在前，None在后的形式
[  [2， 5，22， 55， 11， None， ..， None]，
   [1， 0， None，  ...， None]，  ] 
还是随机的形式
[  [2， None，5，22， 55， 11， None， ..， None]，
   [None，1， 0， None，  ...， None]，  ] 
这两种方式的计算速度是一样的吗？如果一样，是不是实际上dense_shape=[batch_size, 500],比
[batch_size, 5] 的计算时间更慢，因为即使None不参加计算，也要判断这个位置是不是None，当有大量的None时，计算速度就变慢了

**Comment by zakheav** [comment]
sparse tensor转化成dense tensor的结果是你说的第二种形式，因为sparse tensor中有index结构记录了每个value在对应的dense tensor中的位置。
sparse tensor对应的计算有相应的优化，转化成dense之后计算一般会变慢的。

**Comment by Ljl-Jdsk** [comment]
嗯嗯，我明白您的意思，感谢您的超级耐心！我的意思是dense tensor应该是可以表示成第一种形式的，为什么表示成了第二种呢？假如第0个query是"苹果手机"，分成4个字，到表里可以查到这4个字的id 是 4，6，9，10；对应的dense tensor 就表示成[4，6，9，10，None，...，None]，对应的sparse_tenser的index就是[index=[0，1]，[0，2]，[0，3]，[0，4], value=[4，6，9，10], shape=[]]。
是哪个地方导致了dense tensor 的第0行表示成[None, 4, 6, None, 9, 10, None, ...]形式而不是
[4，6，9，10，None，...，None] 呢？
超级感谢！！！

**Comment by zakheav** [comment]
哦哦，你说的这个例子就是[4，6，9，10，None，...，None]形式的，在某些情况下才会变成[None, 4, 6, None, 9, 10, None, ...]，比如index=[[0,2], [0,3], [0,5], [0,6]]的情况。这是tensorflow这样设计的，为了更加通用

**Comment by Ljl-Jdsk** [comment]
嗯嗯，明白啦，得工作后具体理解些业务场景才知道有的地方是怎么回事，怎么应用的！
放学啦，祝您周末愉快，非常感谢！！！

**Comment by zakheav** [comment]
不客气
