### ISSUE TITLE
HashEmbedding ImportError

### ISSUE THREAD

**Issue by aimetrics** [alibaba/euler#188]
try:
  from tf_euler.python.ps_layers import HashEmbedding, HashSparseEmbedding
except ImportError:
  print('Not Found!')
  pass

@alinamimi 请问现在euler不支持HashEmbedding吗?

**Comment by alinamimi** [comment]
HashEmbedding 是在[xdl](https://github.com/alibaba/x-deeplearning) 里面，这段代码是euler + xdl 一起使用的

**Comment by alinamimi** [comment]
euler本身是没有HashEmbedding的
