### ISSUE TITLE
如果有的节点没有采样到，它的embedding就不更新了，这种情况怎么办呢

### ISSUE THREAD

**Issue by pangedeshijie** [alibaba/euler#194]
两个embedding: target_embedding和context_embedding, 
最终保存的只是src对应的target_embedding, 我采src过程中，有一些node没采到，其对应
的embeding就是初始化的，未更新，最终情况怎么办啊！

把targe_embedding和context_embedding合并到一个embedding里是不是比较好啊，这样无论
是src, pos还是neg对应的embedding都会更新，这样会减少 有的node对应的embedding未更新的概率

**Comment by alinamimi** [comment]
训练的是target和context 网络，Embedding是在infer阶段根据feature和target网络得到的

**Comment by pangedeshijie** [comment]
但是最终save的只是target网络，context网络的更新只是辅助而已吧

**Comment by alinamimi** [comment]
是的

**Comment by pangedeshijie** [comment]
所以有的node如果没有被采成src, target网络中的这些点对应的embedding是不更新的，这种情况只能通过多采样来避免吗？

**Comment by alinamimi** [comment]
feature 输入 target 网络 输出 Embedding， 虽然某个src没见过，但feature很大可能是见过的，这种infer出的Embedding是没问题的。src没采样到，本身说明这个点的权重很低，也不是很重要，就算Embedding不更新，影响也不大

**Comment by pangedeshijie** [comment]
哦哦，明白了，感谢
