### ISSUE TITLE
why git clone Failed...THX!

### ISSUE THREAD

**Issue by IvanaXu** [alibaba/euler#20]
```
git clone --recursive https://github.com/alibaba/euler.git
...
# Failed to recurse into submodule path 'third_party/grpc'
```

see https://github.com/IvanaXu/MyLearn/blob/master/Euler/001.install_error.md
SO I GOT IT BY PYPI.

**Comment by renyi533** [comment]
grpc依赖bloaty。因为bloaty里面依赖的libFuzzer的地址在https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer。您试试vpn访问？

**Comment by IvanaXu** [comment]
thx!
