### ISSUE TITLE
Potential Training speed improvement: graphsage - negative sample

### ISSUE THREAD

**Issue by cozilla** [alibaba/euler#216]
我发现目前training speed受限于sample和get features. 
负样本目前采样是`batch_size * self.num_negs`，为何需要去这么多负例？能否整个batch size共用一组负例？你们之前做过类似的实验吗？graph sage paper里面貌似是在一个batch中共享一组负例的？

https://github.com/alibaba/euler/blob/master/tf_euler/python/models/base.py#L60 
```python
  def to_sample(self, inputs):
    batch_size = tf.size(inputs)
    src = tf.expand_dims(inputs, -1)
    pos = euler_ops.sample_neighbor(inputs, self.edge_type, 1,
                                    self.max_id + 1)[0]
    negs = euler_ops.sample_node(batch_size * self.num_negs, self.node_type)
    negs = tf.reshape(negs, [batch_size, self.num_negs])
    return src, pos, negs

```

**Comment by alinamimi** [comment]
num_negs 小的时候，不共享可能会更好。当num_negs大的时候，batch内共享可能会更好。负样本的选取策略是非常丰富和复杂的，我们这里不太可能给出所有的选项，这个只是一个示例。具体的需求，还需要用户进一步开发

**Comment by cozilla** [comment]
谢谢，我打算试一下 :) happy new year!

**Comment by cozilla** [comment]
I did some experiments, and sharing negative sample within the same batch helps a lot.
