### ISSUE TITLE
global sampler is not ok

### ISSUE THREAD

**Issue by wsnooker** [alibaba/euler#228]
INFO: W0226 04:55:20.396543   202 graph.h:198] global sampler is not ok

上述warning是分布式训练时初始化抛出的，请问这个WARNING有什么影响？会导致只在当前worker的局部图中采样，而非全局采样吗？

**Comment by alinamimi** [comment]
这个只影响全局采样，如果不需要全局采样，就不用管

**Comment by wsnooker** [comment]
分布式场景下全局采样是必须的吧？所以这里主要还是 全局节点采样，还是全局边采样的区别？
