### ISSUE TITLE
关于节点标签的问题

### ISSUE THREAD

**Issue by hifree2013** [alibaba/euler#25]
使用半监督GraphSage模型， 在生成数据block时，只有部分节点有标签，其他没有标签的节点如何设置，以给的PPI的数据为例，
![image](https://user-images.githubusercontent.com/47199420/52552136-1eaa1080-2e1a-11e9-9101-7da146c17af0.png)
当节点的标签未知时，float_feature的第0项如何设置

**Comment by yangsiran** [comment]
@hifree2013 设置成空列表就可以了。

**Comment by hifree2013** [comment]
已解决
