### ISSUE TITLE
euler二跳邻居采样

### ISSUE THREAD

**Issue by a370865882** [alibaba/euler#256]
我看到在get_multi_hop_neighbor函数中多跳邻居要根据边的类型采样，意思是我要在生成数据的时候把每个结点的二跳邻居也声明在block里吗？

**Comment by alinamimi** [comment]
不用，先按一跳type采一跳邻居，再根据返回结果和二跳type，采二跳邻居

**Comment by lixusign** [comment]
sample_fanout 这个是采样，get_multi_hop_neighbor 这个是全量k-hop
