### ISSUE TITLE
UnsupervisedModel的负采样方法是不是有些不妥？

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#257]
当前是这么实现的，如果图比较稠密，感觉和pos碰撞概率比较大，不知道作者怎么看？
 negs = euler_ops.sample_node(batch_size * self.num_negs, self.node_type)

**Comment by alinamimi** [comment]
这样做是效率比较高的方式，大部分情况对效果没有影响。如果不想和pos有交集，可以和pos进行一次过滤

**Comment by lixusign** [comment]
嗯嗯，明白了 谢谢
