### ISSUE TITLE
请问binary_feature为空时填什么

### ISSUE THREAD

**Issue by chriskeke95** [alibaba/euler#258]
如题，当节点的某个binary_feature为空时，比如第0个,是 "binary_feature":{"0":""}、"binary_feature":{"0":None}还是直接"binary_feature":{}呢？

**Comment by alinamimi** [comment]
需要根据meta来，参考https://github.com/alibaba/euler/wiki/%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87
如果只是某个节点没有的话，"binary_feature":{"0":""}；如果全部节点都没有的话"binary_feature":{}；
