### ISSUE TITLE
分布式训练多worker出错

### ISSUE THREAD

**Issue by a370865882** [alibaba/euler#261]
![image](https://user-images.githubusercontent.com/37647833/85221332-b09a3400-b3e5-11ea-85ed-74f37842a8c0.png)
同样一份两个文件的数据，我开一个worker可以跑，但是两个worker会如上的错误，同时我发现两个情况下都会有
W0621 17:21:48.989281   255 graph.h:198] global sampler is not ok
是采样的问题吗，还是hdfs的问题，该如何去定位并解决这个问题，采样部分代码没有改动

**Comment by alinamimi** [comment]
把启动命令贴上来看看吧
