### ISSUE TITLE
cora数据集服务端无法启动

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#270]
F /Euler-OpenSource/euler/core/graph/graph_meta.cc:41] Find feature error, Unknown feature name: binary_graph_label

2 shard
10 partition
2 个服务

出现如上情况，导致服务端无法启动。

查找构建数据脚本和数据集 并未有binary相关的feature。

**Comment by zakheav** [comment]
发一下完整的错误日志，这个报错是正常的

**Comment by lixusign** [comment]
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Version: 2.0;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Node count:2708;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Edge count: 5429;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Node feature info:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Name: dense_label, Type: Dense, Dim: 7;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Name: dense_feature, Type: Dense, Dim: 1433;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Edge feature info:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Node type info: 
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Name: train, Index: 0;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Name: test, Index: 1;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Edge type info: 
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Name: train, Index: 0;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:Name: train_removed, Index: 1;
Mon Jun 29 17:40:33 2020[1,0]<stderr>:
Mon Jun 29 17:40:33 2020[1,0]<stderr>:2020-06-29 17:40:34.000123: W /Euler-OpenSource/euler/core/graph/graph_builder.cc:168] Graph Node Count:1354
Mon Jun 29 17:40:33 2020[1,0]<stderr>:2020-06-29 17:40:34.000154: W /Euler-OpenSource/euler/core/graph/graph_builder.cc:169] Graph Edge Count:0
Mon Jun 29 17:40:33 2020[1,0]<stderr>:2020-06-29 17:40:34.000173: W /Euler-OpenSource/euler/core/graph/graph.cc:334] Build Node Global Sampler...
Mon Jun 29 17:40:33 2020[1,0]<stderr>:2020-06-29 17:40:34.000182: W /Euler-OpenSource/euler/core/graph/graph.cc:341] Node type num:2
Mon Jun 29 17:40:33 2020[1,0]<stderr>:2020-06-29 17:40:34.000491: W /Euler-OpenSource/euler/core/graph/graph_builder.cc:156] Graph build completely!
Mon Jun 29 17:40:33 2020[1,0]<stderr>:2020-06-29 17:40:34.000525: W /Euler-OpenSource/euler/core/graph/graph.cc:111] Build graph successfully, shard Index: 0, shard number: 2, data path: /home/hadoop-aipnlp/cephfs/data/lixu05/euler2_data/cora_data/euler, sampler_type: node
Mon Jun 29 17:40:41 2020[1,0]<stderr>:2020-06-29 17:40:41.614142: W /Euler-OpenSource/euler/service/grpc_server.cc:166] Missing Index directory, skip loading index.
Mon Jun 29 17:40:41 2020[1,0]<stderr>:2020-06-29 17:40:41.614229: E /Euler-OpenSource/euler/core/graph/graph.cc:434] global sampler is not ok
Mon Jun 29 17:40:41 2020[1,0]<stderr>:2020-06-29 17:40:41.614244: F /Euler-OpenSource/euler/core/graph/graph_meta.cc:41] Find feature error, Unknown feature name: binary_graph_label
Mon Jun 29 17:40:41 2020[1,1]<stderr>:2020-06-29 17:40:41.617176: W /Euler-OpenSource/euler/service/grpc_server.cc:166] Missing Index directory, skip loading index.
Mon Jun 29 17:40:41 2020[1,1]<stderr>:2020-06-29 17:40:41.617268: E /Euler-OpenSource/euler/core/graph/graph.cc:434] global sampler is not ok
Mon Jun 29 17:40:41 2020[1,1]<stderr>:2020-06-29 17:40:41.617281: F /Euler-OpenSource/euler/core/graph/graph_meta.cc:41] Find feature error, Unknown feature name: binary_graph_label
Mon Jun 29 17:40:41 2020[1,0]<stderr>:2020-06-29 17:40:41.702683: W /Euler-OpenSource/euler/service/grpc_server.cc:207] Server started successfully!
Mon Jun 29 17:40:41 2020[1,1]<stderr>:2020-06-29 17:40:41.732736: W /Euler-OpenSource/euler/service/grpc_server.cc:207] Server started successfully!
2020-06-29 17:40:48: *** shutting down gRPC client since JVM is shutting down
2020-06-29 17:40:48: *** server shut down

**Comment by zakheav** [comment]
这个euler已经正常启动了

**Comment by lixusign** [comment]
好的 可能是其他原因 多谢。

另外  F 不是等于  Fault吗？  
F /Euler-OpenSource/euler/core/graph/graph_meta.cc:41] Find feature error, Unknown feature name: binary_graph_label
这个具体的含义是什么呢？ 尚未找到为啥找binarylabel的具体逻辑

**Comment by lixusign** [comment]
发现服务是自己退出了 现在要这么保持服务？
https://github.com/alibaba/euler/blob/a7b50ad5b3755a7780e21f914d5dd69fb8c5219a/tf_euler/scripts/start_service.py

**Comment by zakheav** [comment]
> 好的 可能是其他原因 多谢。
> 
> 另外 F 不是等于 Fault吗？
> F /Euler-OpenSource/euler/core/graph/graph_meta.cc:41] Find feature error, Unknown feature name: binary_graph_label
> 这个具体的含义是什么呢？ 尚未找到为啥找binarylabel的具体逻辑

这里是为了在一张图模式下支持多张图设计的，之后会把这个log删除掉

**Comment by zakheav** [comment]
> 发现服务是自己退出了 现在要这么保持服务？
> https://github.com/alibaba/euler/blob/a7b50ad5b3755a7780e21f914d5dd69fb8c5219a/tf_euler/scripts/start_service.py
> 
> sleep(xxxxx) ??

是的
