### ISSUE TITLE
关于2.0新增GQL编译执行引擎的性能

### ISSUE THREAD

**Issue by Hacky-DH** [alibaba/euler#271]
2.0新增的GQL编译执行引擎，减少了运行过程中Euler和tensorflow的交互次数，官方有没有和1.0的性能对比数据？同样的数据量采样能减少多少？

**Comment by zakheav** [comment]
减少的次数主要和使用的模型相关

**Comment by zakheav** [comment]
这个和具体的GQL语句有关，在我们实验中，batch size 1024，每个节点获取5+5个异构邻居，同时获取根节点与邻居的feature，使用euler1耗时是euler2的130%～140%。考虑到测试中获取图结构和数据在timeline的占比大概为50%，因此单纯euler1查询图的时间是euler2的160%左右

**Comment by lixusign** [comment]
也借楼问下，之前服务端的多副本replicas， 这次去掉了吧？ 感觉多副本空耗内存，并发sample提升有限

**Comment by zakheav** [comment]
没有去掉，这个可以自己设定是否需要replica

**Comment by Hacky-DH** [comment]
@zakheav 好的 谢谢
