### ISSUE TITLE
Core dump 问题

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#274]
estimator 分布式训练遇到这个问题，不知道如何解决
euler里面有用到java的地方吗？

tf 1.12
cora 数据集
2 worker
1 chief
1 ps
euler2.0 

# Problematic frame:
# [thread 140471654233856 also had an error]
C  [libeuler_core.so+0x354055]  euler::AppendMerge::Compute(euler::DAGNodeProto const&, euler::OpKernelContext*)+0x2b5
#
# Core dump written. Default location: [thread 140471629448448 also had an error]

**Comment by zakheav** [comment]
提供一下使用的什么算法，其中导致core的代码段麻烦定位一下，以及完整的gdb调试信息麻烦提供一下

**Comment by zakheav** [comment]
提供一下使用的什么算法，以及完整的gdb调试信息麻烦提供一下

**Comment by lixusign** [comment]
感觉是其他问题导致的，我再看下。

**Comment by lixusign** [comment]
奇怪了 单机多进程estimator就没事，多机分布式训练就core了，程序是release版本？没有gdb的dump

**Comment by alinamimi** [comment]
> 奇怪了 单机多进程estimator就没事，多机分布式训练就core了，程序是release版本？没有gdb的dump

你是源码编译的？有没有打开core dump？

**Comment by lixusign** [comment]
我当前yum直接安装的，core dump 还木有看，换了个算法 ，发现没有问题了，但是在eva服务上会发生

File "tf_euler/python/mp_utils/base_gnn.py", line 89, in __call__
    edge_attr=edge_attr)
  File "tf_euler/python/mp_utils/base_gnn.py", line 72, in calculate_conv
    return conv(inputs, edge_index, size=size, edge_attr=edge_attr)
  File "tf_euler/python/convolution/sage_conv.py", line 37, in __call__
    out = self.apply_node(out, x[0])
  File "tf_euler/python/convolution/sage_conv.py", line 44, in apply_node
    return self.self_fc(x) + self.neigh_fc(aggr_out)
  File "tensorflow/python/layers/base.py", line 343, in __call__
    raise ValueError('Input graph and Layer graph are not the same: %s' % e)
ValueError: Input graph and Layer graph are not the same: Tensor("MPGather:0", shape=(?, 1433), dtype=float32) is not from the passed-in graph.

Input graph and Layer graph are not the same  ？用的还是cora数据集、graphsage_supervized

**Comment by ergouy** [comment]
为什么我按照教程安装完成之后找到tf_euler这个包，还有一些其他包也找不到？
