### ISSUE TITLE
Euler-2.0: 在项目根目录找不到图转化工具脚本：euler/tools/gen_partitioned_data.sh，是不是被删除了？

### ISSUE THREAD

**Issue by jmzhoulab** [alibaba/euler#275]

**Comment by jmzhoulab** [comment]
tools目录内容只有如下几个内容，并未找到gen_partitioned_data.sh
`
work@server1:~/euler$ ll tools/
total 24
drwxrwxr-x  5 work work 4096 Jun 30 23:30 ./
drwxrwxr-x 12 work work 4096 Jun 30 23:30 ../
-rw-rw-r--  1 work work   35 Jun 30 23:30 .gitignore
-rw-rw-r--  1 work work    0 Jun 30 23:30 CMakeLists.txt
drwxrwxr-x  2 work work 4096 Jun 30 23:30 pip/
drwxrwxr-x  2 work work 4096 Jun 30 23:30 start_zk/
drwxrwxr-x  2 work work 4096 Jun 30 23:30 test_data/
work@server1:~/euler$
work@server1:~/euler$
`

**Comment by jmzhoulab** [comment]
tools目录内容只有如下几个内容，并未找到gen_partitioned_data.sh
```
work@server1:~/euler$ ll tools/
total 24
drwxrwxr-x  5 work work 4096 Jun 30 23:30 ./
drwxrwxr-x 12 work work 4096 Jun 30 23:30 ../
-rw-rw-r--  1 work work   35 Jun 30 23:30 .gitignore
-rw-rw-r--  1 work work    0 Jun 30 23:30 CMakeLists.txt
drwxrwxr-x  2 work work 4096 Jun 30 23:30 pip/
drwxrwxr-x  2 work work 4096 Jun 30 23:30 start_zk/
drwxrwxr-x  2 work work 4096 Jun 30 23:30 test_data/
work@server1:~/euler$
work@server1:~/euler$
```

**Comment by zakheav** [comment]
在 euler根项目中的euler/tools/下面，不在tools/下面

**Comment by jmzhoulab** [comment]
> 在 euler根项目中的euler/tools/下面，不在tools/下面
感谢，找到了
