### ISSUE TITLE
Euler 2.0 PyPI GCC的版本

### ISSUE THREAD

**Issue by Hacky-DH** [alibaba/euler#276]
请问，Euler 2.0 在PyPI的版本用的什么GCC的版本？

我在centos7安装了euler2.0，gcc版本是4.8.5

我执行`python -m tf_euler`报错如下

```
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
```

**Comment by alinamimi** [comment]
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
cmake version 3.10.2

**Comment by Hacky-DH** [comment]
Thanks
