### ISSUE TITLE
edge type不连续

### ISSUE THREAD

**Issue by johnzhang1999** [alibaba/euler#278]
请问edge_type可是不连续的int么
如果可以的话，请问建图时在meta info json里写edge_type_num是写edge types的总数还是最大编号？

**Comment by zakheav** [comment]
对于euler2.0来说，edge type支持string类型，并且不需要写meta info json了，在生成二进制数据过程中会自动生成

**Comment by johnzhang1999** [comment]
> 对于euler2.0来说，edge type支持string类型，并且不需要写meta info json了，在生成二进制数据过程中会自动生成

还没升级到2.0，请问之前的版本呢

**Comment by zakheav** [comment]
顶点类型、边类型，以及点边上的三种属性均独自从0开始以连续的非负整数命名

> > 对于euler2.0来说，edge type支持string类型，并且不需要写meta info json了，在生成二进制数据过程中会自动生成
> 
> 还没升级到2.0，请问之前的版本呢
