### ISSUE TITLE
fastgcn分布式训练报错

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#280]
*** End of error message ***
2020-07-08 16:16:24.451248:  /Euler-OpenSource/euler/core/graph/graph.h:97] Edge Map size is 0. Edges need to be loaded before use GetEdgeByID.

导致服务端  core dump

**Comment by zakheav** [comment]
https://github.com/alibaba/euler/blob/master/euler/python/start_service.py#L74
默认状态为了降低mem占用，没有加载edge map

**Comment by lixusign** [comment]
麻烦简要描述下：
    NODE = 1
    EDGE = 2
    NODE_SAMPLER = 4
    EDGE_SAMPLER = 8
    DEFAULT_MODULE = NODE | NODE_SAMPLER

控制哪些OP或底层结构

**Comment by zakheav** [comment]
euler的底层数据结构包含了四个：
node表，存储了node的attr，node的邻接表，
edge表，存储了edge的sttr
node sampler：用于全局node采样，是一个分type的alias table sampler
edge sampler：用于全局edge采样，是一个分type的alias table sampler

**Comment by lixusign** [comment]
3q
