### ISSUE TITLE
tensorflow客户端报ids size != weights size, init error 是什么错误

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#281]
E0710 00:44:00.415828   430 compact_weighted_collection.h:93] ids size != weights size, init error

**Comment by lixusign** [comment]
sample_neighbor 时候发生

**Comment by lixusign** [comment]
sage unsupervised ， 并且导致服务端core dump

**Comment by zakheav** [comment]
可以提供一下你的sage的配置代码。

**Comment by lixusign** [comment]
是我docker的问题貌似  我再看看
