### ISSUE TITLE
tf高级接口的所有op操作都是在cpu上执行的吗？

### ISSUE THREAD

**Issue by wangguangyuan** [alibaba/euler#3]
首先感谢能够开源这么好的框架，我现有个疑惑想请教一下，我记得tf的操作会首先放到gpu上，而我看咱们的tf接口只是实现了cpp。所以有些疑惑如果用tf调咱们的框架是否需要其它配置？

**Comment by yangsiran** [comment]
配合TensorFlow使用不需要任何特殊的配置。由于图的存储和计算目前都是host在cpu上的，所以op的实现也是cpu的，运行的时候也是被放置在cpu上。而其他的op以及图op和模型训练的交互仍然是走的TensorFlow的逻辑。

**Comment by treper** [comment]
> 配合TensorFlow使用不需要任何特殊的配置。由于图的存储和计算目前都是host在cpu上的，所以op的实现也是cpu的，运行的时候也是被放置在cpu上。而其他的op以及图op和模型训练的交互仍然是走的TensorFlow的逻辑。

支持单机训练吗？

**Comment by renyi533** [comment]
支持单机的。需要图比较小能单机存下。
