### ISSUE TITLE
通过pip安装和编译安装有什么区别？

### ISSUE THREAD

**Issue by 2shou** [alibaba/euler#32]
服务器上通过pip安装一切正常，但是通过编译安装总会在安装zookeeper的那行报错，请问是什么原因？

**Comment by yangsiran** [comment]
@2shou 麻烦提供一下具体的错误日志？

**Comment by 18521344596** [comment]
CMake Error at cmake/grpc.cmake:4 (add_subdirectory):
  The source directory

    /home/abc/euler-master/third_party/grpc

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:24 (include)


CMake Error at cmake/googletest.cmake:3 (add_subdirectory):
  The source directory

    /home/abc/euler-master/third_party/googletest

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)


CMake Error at cmake/glog.cmake:2 (add_subdirectory):
  The source directory

    /home/abc/euler-master/third_party/glog

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:26 (include)


CMake Error at cmake/zookeeper.cmake:3 (add_subdirectory):
  add_subdirectory given source
  "/home/abc/euler-master/third_party/zookeeper/zookeeper-client/zookeeper-client-c"
  which is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)


-- tensorflow_framework library found: in /home/abc/.local/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so
-- Configuring incomplete, errors occurred!

**Comment by 18521344596** [comment]
追加cmakeerror.log如下
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/abc/euler-master/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_7dcb0/fast"
/usr/bin/make -f CMakeFiles/cmTC_7dcb0.dir/build.make CMakeFiles/cmTC_7dcb0.dir/build
make[1]: Entering directory '/home/abc/euler-master/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_7dcb0.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -fPIE   -o CMakeFiles/cmTC_7dcb0.dir/CheckSymbolExists.cxx.o -c /home/abc/euler-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
Linking CXX executable cmTC_7dcb0
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7dcb0.dir/link.txt --verbose=1
/usr/bin/c++       CMakeFiles/cmTC_7dcb0.dir/CheckSymbolExists.cxx.o  -o cmTC_7dcb0 
CMakeFiles/cmTC_7dcb0.dir/CheckSymbolExists.cxx.o: In function `main':
CheckSymbolExists.cxx:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_7dcb0.dir/build.make:97: recipe for target 'cmTC_7dcb0' failed
make[1]: *** [cmTC_7dcb0] Error 1
make[1]: Leaving directory '/home/abc/euler-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_7dcb0/fast' failed
make: *** [cmTC_7dcb0/fast] Error 2

**Comment by 18521344596** [comment]
能麻烦帮忙看一下问题出在哪吗

**Comment by yangsiran** [comment]
@18521344596 你的三方依赖目录里面应该没有内容。获取源码的时候需要加上`--recursive`：
```bash
git clone --recursive https://github.com/alibaba/euler.git
```
或者在git workspace下执行：
```bash
git submodule update --init --recursive
```

**Comment by 2shou** [comment]
定位是`ant compile_jute`语句出错了，原因是`网络不可达`，服务器确实是限制了外网连接的。好奇的是，为什么pip安装是没有错，难道是因为pip安装不要求zookeeper么？

**Comment by chengenbao** [comment]
ant compile的时候会下载尝试的jar包，pip安装的时候是从pip源下载已经编译好的pip包

**Comment by ergouy** [comment]
@chengenbao @2shou 请教一下我按照官方教程安装完总是缺一些包或者命令
