### ISSUE TITLE
English description

### ISSUE THREAD

**Issue by sun-xiaoyu** [alibaba/euler#37]
Hi,

Could you please add an English description? It would be really nice.
Thanks a lot for your work!

**Comment by renyi533** [comment]
We do not have the plan to provide systematic English documents now. 
But we also think this is important. Just not enough resource for now.

**Comment by spebern** [comment]
I'd be happy to help with translations if you are interested

**Comment by yangsiran** [comment]
Hi, all.

Euler is now updated with English documents. Thanks.
