### ISSUE TITLE
关于计算资源和复杂度的咨询

### ISSUE THREAD

**Issue by F36** [alibaba/euler#40]
刚切入到图神经网络这块，之前也一直在调研图神经网络，效果不错，目前工作也涉及到这些，以下有几点比较关切，还望能够得到靠谱的建议。
1.关于计算资源的，如果是上亿规模的节点，以及与之相对应的量级的边，用多大的机器配置比较合适？
2.关于数据倒入的问题，怎么样能够快速生成适合euler格式的json数据？
3.spark里面的GraphX也是专门处理图的，图计算引擎是基于pregrel模式，存储是基于点分割，据说也是目前业界的主流。那么euler跟graphX之间的关系是怎么样的呢？相互补充，还是包含？
4.目前来看euler主要是图计算，图模型，图存储这块看到的不多，请问这是打算用其它工具吗？还是考虑后续开发和改进呢？
Thanks。

**Comment by renyi533** [comment]
1. 取决于您所用的机器的内存，需要边点partition后可以放到多机器内存里。目前euler不支持ssd。
2.如果是比较大的图，利用类似hadoop的mapreduce系统比较合适。我们提供了java的类，可以在hadoop里边使用。
3. GraphX主要是传统的图分析，不太方便与深度学习集成。Euler主要是深度图学习的场景。
4. 图存储目前Euler就是存储在内存中的，也是自己实现的。

**Comment by F36** [comment]
> 1. 取决于您所用的机器的内存，需要边点partition后可以放到多机器内存里。目前euler不支持ssd。
>    2.如果是比较大的图，利用类似hadoop的mapreduce系统比较合适。我们提供了java的类，可以在hadoop里边使用。
> 2. GraphX主要是传统的图分析，不太方便与深度学习集成。Euler主要是深度图学习的场景。
> 3. 图存储目前Euler就是存储在内存中的，也是自己实现的。

了解，thanks.
