### ISSUE TITLE
无监督算法如LINE / DeepWalk等产生的embedding如何保存到HDFS？

### ISSUE THREAD

**Issue by 2shou** [alibaba/euler#43]
看了源码，`run_save_embedding`接口貌似只支持写入到本地`model_dir`，并不支持HDFS路径？

**Comment by yangsiran** [comment]
@2shou 目前是这样的，这里还没有分布式的保存embedding或保存embedding到分布式文件系统的功能。

**Comment by 2shou** [comment]
了解了，后续你们有开发保存到HDFS功能的计划吗？
