### ISSUE TITLE
lasgnn和lshne还不能使用吗?

### ISSUE THREAD

**Issue by yaochitc** [alibaba/euler#49]
看了下run_loop.py,lasgnn并没有加到里面,而lshne的超参都是固定的值,请问是什么原因呢?

**Comment by YanZhangN** [comment]
是的，目前这两个内部模型还没有正是在model zoo里发布，近期的更新会增加这两个模型。

**Comment by yaochitc** [comment]
好的，3q

**Comment by formath** [comment]
@YanZhangN lshne何时能发布呢？
