### ISSUE TITLE
关于分布式训练导致测试过程F1下降问题

### ISSUE THREAD

**Issue by lixusign** [alibaba/euler#53]
欧拉你好，我们这边在测试官方提供的PPI数据过程中，单机训练默认参数同样step下，f1 = 0.6左右，但是在分布式环境部署后同样版本的欧拉系统 f1训练结束后降低到0.36左右。 数据切分方式是直接切分，比如固定block数切分。请问f1 score下降的主要原因是什么？

PS: 分布式训练采用 1ps + 3worker

**Comment by lixusign** [comment]
另外需要问下：
W0304 12:40:01.660442 17948 graph.h:148] global sampler is not ok 
造成训练过程中，上面这个的原因主要有哪些？

**Comment by yangsiran** [comment]
@lixusign 分布式训练需要把block按照node_id的模切分到不同文件中的，麻烦提供一下您的数据文件列表以及其中大致包含的id？
另外一个可能性是需要调整学习率，加大并发的情况下可能需要一定程度的调小。

**Comment by yangsiran** [comment]
> 另外需要问下：
> W0304 12:40:01.660442 17948 graph.h:148] global sampler is not ok
> 造成训练过程中，上面这个的原因主要有哪些？

`tf_euler.initialize_shared_graph(..., global_sampler_type='node', ...)`的情况下就是会打印这条日志的，不影响除了边采样以外的功能的使用。使用`tf_euler.initialize_shared_graph(..., global_sampler_type='all', ...)`就不会打印这条日志了。

**Comment by lixusign** [comment]
你好，我跑的是官方ppi示例，我当前的情况是evo过程：

测试模式/f1 | f1-score, 学习率0.01
单机同进程 | 0.611114382744
1ps + 1worker | 0.604843258858
1ps + 2worker | 0.558323383331
1ps + 3worker | 0.525012552738

好的 我先调整下学习率尝试下。

**Comment by lixusign** [comment]
你好，调整学习率之后 效果不明显 依然没有提升，请问数据分片是否会有问题，当前数据分片策略：

直接按照block 条目进行切割，比如统计出当前有100个block， 则按照数据直接split -l切割。
具体比如起3个shard  走切割的6个partition. 本身应该没有问题。

**Comment by lixusign** [comment]
其他超参数没有调整，当前3worker  故learning_rate 调整到了0.002 下降到原来的5分之一

**Comment by yangsiran** [comment]
> 你好，调整学习率之后 效果不明显 依然没有提升，请问数据分片是否会有问题，当前数据分片策略：
> 
> 直接按照block 条目进行切割，比如统计出当前有100个block， 则按照数据直接split -l切割。
> 具体比如起3个shard 走切割的6个partition. 本身应该没有问题。

@lixusign PPI这个数据有56945个顶点，如果分成6个partition，则所有模6等于0的点必须在xx_0.dat中，模6等于1的点必须在xx_1.dat中，如此类推。其他的分片方法都是不行的。

**Comment by lixusign** [comment]
好的，我采用此方式 处理下数据

**Comment by lixusign** [comment]
已经搞定,非常感谢

**Comment by ivankxt** [comment]
> 已经搞定,非常感谢

hello @lixusign , 我跑的也是官方ppi示例，请问切割的6个partition的具体数据的分片方法是？

**Comment by ivankxt** [comment]
> 已经搞定,非常感谢

请问具体是怎么解决的？我也是按照求模的方式切割数据，但是F1没有提升（1ps + 2worker），请指教，谢谢。

**Comment by ivankxt** [comment]
> 好的，我采用此方式 处理下数据


> 已经搞定,非常感谢

@lixusign 请问具体是怎么解决的？我也是按照求模的方式切割数据，但是F1没有提升（1ps + 2worker），请指教，谢谢。
