### ISSUE TITLE
关于LasGNN的sampling策略的请教

### ISSUE THREAD

**Issue by BenchengY** [alibaba/euler#55]
你好！我看了下LasGNN的介绍（https://github.com/alibaba/euler/wiki/LasGNN ），
对于layer-wise的sample， LasGNN是根据网络中每一层学得的权重W进行加权采样的，但是，sampling这个操作不应该在预处理的时候做的嘛，如何根据训练过程的W进行sample？
不是特别理解，能否详细介绍下？
此外，我在代码中没太找到对应的操作代码，能否指明一下是在哪一部分？谢谢了！

**Comment by yangsiran** [comment]
@BenchengY layer-wise sampling是根据图中的顶点权重做的，不是根据模型的权重做的。目前repo里面的代码是简化版的，仍然是node-wise的，具体的sample部分的代码在：
https://github.com/alibaba/euler/blob/e2785eca70e7e4f37d73ac4ce64a3059b0385dc7/tf_euler/python/encoders.py#L290

**Comment by BenchengY** [comment]
@yangsiran 哦哦。这里的权重指的就是graph中边的权重做的呀~好的，谢谢了~
