### ISSUE TITLE
分布式训练shared_num>1,hdfs数据都download到一个里面

### ISSUE THREAD

**Issue by chrisxu2016** [alibaba/euler#64]
我通过pip安装的euler，然后使用[分布式训练的示例](https://github.com/alibaba/euler/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E5%88%86%E5%B8%83%E5%BC%8F%E8%AE%AD%E7%BB%83)
执行该脚本后，查询/tmp/log.worker.0的日志，一直卡在metainfo那里，通过[这里](https://github.com/alibaba/euler/issues/36#issuecomment-465918916) 了解到是因为shared_num>1的缘故， 修改run_loop.py里面，将shared_num固定为1后，可以正常执行。

查询修改之前的日志 /tmp/log.worker.1 的日志，发现是shared_idx=1的 shared 没有数据文件
![image](https://user-images.githubusercontent.com/18379485/54422571-c7190080-4749-11e9-9ed6-31f6ea99706f.png)
实际该hdfs路径下的数据都下载到了shared_index=0的里面，请问怎样让shared_num>1时， 每个shared都能下载到数据。

ps:  我将该数据切分成4个和100个part时，shared=2都有同样的问题

**Comment by yangsiran** [comment]
需要设置shard_num=2码，然后在worker 0里使得shard_idx=0，在worker 1里使得shard_idx=1。不然是不会做数据切分的。你一开始的问题应该是因为shard 1没能成功的启动。

**Comment by chrisxu2016** [comment]
问题已经解决了
不是这个原因, hdfs目录下的的分片文件的命名方式有问题， 这个日志里面显示的partition number=1. 我后面将hdfs下的文件分拣改成 ***_index.dat格式就可以了。参考代码euler/core/graph_engine.cc
![image](https://user-images.githubusercontent.com/18379485/54472236-25a0b600-4800-11e9-90b6-48aa62744e76.png)
所以你们给的二进制数据转换文件GraphDataParser.java是不是也需要改一下，增加一个"_"
![image](https://user-images.githubusercontent.com/18379485/54472257-71535f80-4800-11e9-93ec-cdc6d33beae9.png)

**Comment by shawnspace** [comment]
请问一下在指定分布式训练参数时，其中的euler_zk_path应该指定成什么呀？我是在localhost启动了一个zk服务，由于之前没接触过zk，所以不太理解应该做些什么

**Comment by yangsiran** [comment]
@shawnspace 就是分布式的euler依赖一个ZK服务，您需要实现部署一套ZK服务（可以是简单的standalone或者是cluster）。然后在ZK上创建一个节点，例如/euler_example。然后在euler的euler_zk_path里面填刚才创建的这个路径就可以了。
