### ISSUE TITLE
id.txt和embedding.npy文件的id是一一对应的吗？

### ISSUE THREAD

**Issue by F36** [alibaba/euler#65]
mode = save embedding下，会得到两份文件:embedding.npy和id.txt，其中id.txt的生产逻辑是range(max_id+1)，那么这个id.txt和embedding文件的关系是一一对应的吗？

**Comment by yangsiran** [comment]
@F36 是一一对应的。

**Comment by F36** [comment]
> @F36 是一一对应的。

了解，谢谢。
