### ISSUE TITLE
OSError: libjvm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by baymaxKevin** [alibaba/euler#7]
执行python ppi_data.py报错，检查下java环境变量，export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export LD_LIBRARY_PATH=$JAVA_HOME/lib/server:$LD_LIBRARY_PATH，这里$JAVA_HOME/lib文件夹下并没有server，是还缺少什么吗

**Comment by yangsiran** [comment]
@baymaxKevin 请问你的发行版和安装jvm的方式是什么？

**Comment by baymaxKevin** [comment]
Euler是PyPI安装，jdk是sudo add-apt-repository ppa:webupd8team/java
sudo apt-get install oracle-java8-installer安装的

**Comment by yangsiran** [comment]
@baymaxKevin 你这个安装的libjvm.so在/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server下面。你可以尝试：
```bash
export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
export LD_LIBRARY_PATH=$JAVA_HOME/lib/amd64/server:$LD_LIBRARY_PATH
```

**Comment by baymaxKevin** [comment]
问题已解决

**Comment by F36** [comment]
> 问题已解决

同样问题，red hat，已经解决。
