### ISSUE TITLE
编译安装时提示出错——/usr/bin/ld: cannot find -lhdfs

### ISSUE THREAD

**Issue by zhangwei730** [alibaba/euler#71]
euler项目维护者，你们好！先感谢你们的付出。
然后，在我编译安装时，至 make -j 32 这一步骤，出现了一下的错误：

[ 21%] Built target signalhandler_unittest
[ 21%] Built target gtest_main
[ 25%] Built target libprotobuf
[ 25%] Built target demangle_unittest
[ 26%] Built target logging_unittest
[ 26%] Built target symbolize_unittest
[ 26%] Built target stl_logging_unittest
[ 26%] Built target fast_weighted_collection_test
[ 26%] Built target utilities_unittest
[ 27%] Built target compact_weighted_collection_test
[ 27%] Built target net_util_test
[ 28%] Built target zookeeper
[ 29%] Built target gmock_main
[ 29%] Built target cli
[ 29%] Built target load_gen
[ 29%] Built target common
[ 29%] Linking CXX executable server_monitor_test
[ 29%] Linking CXX executable local_file_io_test
[ 29%] Built target core
[ 29%] Linking CXX executable local_graph_test
/usr/bin/ld: cannot find -lhdfs
collect2: error: ld returned 1 exit status
make[2]: *** [euler/common/local_file_io_test] Error 1
make[1]: /usr/bin*** [euler/common/CMakeFiles/local_file_io_test.dir/all] Error 2
/ld: cannotmake[1]:  *** Waiting for unfinished jobs....
find -lhdfs
collect2: error: ld returned 1 exit status
make[2]: *** [euler/common/server_monitor_test] Error 1
make[1]: *** [euler/common/CMakeFiles/server_monitor_test.dir/all] Error 2
**/usr/bin/ld: cannot find -lhdfs**
collect2: error: ld returned 1 exit status
[ 33%] Built target libprotoc
make[2]: *** [euler/core/local_graph_test] Error 1
make[1]: *** [euler/core/CMakeFiles/local_graph_test.dir/all] Error 2
[ 33%] Built target crypto
[ 44%] Built target grpc_unsecure
make: *** [all] Error 2

我用 locate lhdfs 查找时，发现系统并没有找到。
我搜索了很多回答，但是都没提及如何使得系统中有 lhdfs 这个工具。

所以，想在此向你们提出问题，以期获得回复并解决当务之急，谢谢，不胜感激！

**Comment by xuetf** [comment]
请问楼主最好怎么解决的？环境变量设置好了，还是报错

**Comment by yangsiran** [comment]
@xuetf 执行
```bash
echo $LIBRARY_PATH
echo $LD_LIBRARY_PATH
```
再看看里面的路径有没有包含libhdfs.so的

**Comment by xuetf** [comment]
> @xuetf 执行
> 
> ```shell
> echo $LIBRARY_PATH
> echo $LD_LIBRARY_PATH
> ```
> 
> 再看看里面的路径有没有包含libhdfs.so的

谢谢。我的机器是RetHat的，不知道其他同学是否遇到这样的问题。这几个步骤我都试过了，都是可以找到libhdfs.so的，包括加入到bashrc里头也都试过。结果编译的时候就是找不到。非常迷（Ubuntu试过没有这样的问题）。

最后的解决方法，我手动修改了CMakeLists.txt，加了一句话，
link_directories("/usr/local/hadoop-2.9.2/lib/native" "/usr/lib/jvm/java/jre/lib/amd64/server")
编译通过了。
再次感谢。

**Comment by yangsiran** [comment]
这个依赖确实用CMake来管理比用环境变量更好。@xuetf
