### ISSUE TITLE
docker 编译出错

### ISSUE THREAD

**Issue by augustus0725** [alibaba/euler#74]
Step 16/16 : RUN cd /tmp/Euler/third_party/zookeeper &&     ((cd zookeeper-client/zookeeper-client-c;       [ -e generated/zookeeper.jute.h ] && [ -e generated/zookeeper.jute.c ]) ||      ant compile_jute) &&     cd /tmp/Euler &&     mkdir -p /tmp/build && cd /tmp/build &&     cmake /tmp/Euler &&     make -j $(expr $(nproc) \* 2) &&     cd /tmp/Euler &&     python tools/pip/setup.py install &&     rm -rf /tmp/Euler /tmp/build
 ---> Running in 2fbd3316c9be
/bin/sh: 1: cd: can't cd to zookeeper-client/zookeeper-client-c
Buildfile: build.xml does not exist!
Build failed
The command '/bin/sh -c cd /tmp/Euler/third_party/zookeeper &&     ((cd zookeeper-client/zookeeper-client-c;       [ -e generated/zookeeper.jute.h ] && [ -e generated/zookeeper.jute.c ]) ||      ant compile_jute) &&     cd /tmp/Euler &&     mkdir -p /tmp/build && cd /tmp/build &&     cmake /tmp/Euler &&     make -j $(expr $(nproc) \* 2) &&     cd /tmp/Euler &&     python tools/pip/setup.py install &&     rm -rf /tmp/Euler /tmp/build' returned a non-zero code: 1

**Comment by buaawht** [comment]
同样问题，请问问题解了么？

**Comment by yangsiran** [comment]
@augustus0725 @buaawht 请问git clone的时候加--recursive参数了吗？workspace下面的third_party/zookeeper目录下面的内容是什么？

**Comment by augustus0725** [comment]
不好意思 @yangsiran  后来发现这个项目依赖了其他项目 编成功了
