### ISSUE TITLE
PS参数分片的问题

### ISSUE THREAD

**Issue by wyunchi1990** [alibaba/euler#76]
我们看到默认的embedding layer里面是没有加参数分片的，于是我们在variable上自己加了partitioner，但是发现单个ps的时候结果是正常的，当ps数量超过一个之后训练出来的模型就是错误的，请问这个是我们使用的时候方式不对么？

**Comment by renyi533** [comment]
我们建议把一个layer加入到一个var scope。这个scope可以设置一个partiioner，这样layer逻辑和partition解耦合。

超过一个这个问题。一般是你设计的partition是by mod。这样测试时候ps个数和训练需要是一样的
