### ISSUE TITLE
分布式训练

### ISSUE THREAD

**Issue by baymaxKevin** [alibaba/euler#8]
在用euler做分布式训练，启动bash中--euler_zk_path要设置什么参数？我分别尝试不设置--euler_zk_path和设置--euler_zk_path本地路径（/data/baymax/euler_zk），控制台和log也没有输出，是不是设置的问题？如果不是设置问题，怎么查看分布式训练过程（考虑既没有控制输出，本地log也没输出）？

**Comment by yangsiran** [comment]
@baymaxKevin Euler的分布式使用依赖一个ZooKeeper服务来协调，`--euler_zk_path`需要填写ZK服务上一个可以使用的节点，默认是`/tf_euler`。一个启动的例子是：

```bash
bash tf_euler/scripts/dist_tf_euler.sh \
  --data_dir hdfs://namenode.com:9000/euler_data/reddit \
  --euler_zk_addr zookeeper.com:2181 --euler_zk_path /tf_euler \
  --max_id 232965 --feature_idx 1 --feature_dim 602 --label_idx 0 --label_dim 1 --num_class 41 \
  --model graphsage_supervised --mode train
```

[这个脚本](https://github.com/alibaba/euler/blob/master/tf_euler/scripts/dist_tf_euler.sh)会把所有输出都打印到`/tmp/log.worker.{0,1}`中，你可以查看一下这两个文件有没有被创建，以及有没有内容。

**Comment by baymaxKevin** [comment]
zk服务是在euler服务所在机器，还是远程hdfs集群？

**Comment by yangsiran** [comment]
@baymaxKevin 都可以，只要是训练进程能访问到的ZK服务都行，就是需要事先先启动好。

**Comment by baymaxKevin** [comment]
zk在euler服务的机器启动，命令如下：
`bash scripts/dist_tf_euler.sh \
  --data_dir hdfs://bjn-1:8020/user/ljz/data/ppi \
  --euler_zk_addr localhost:2181 --euler_zk_path tf_euler \
  --max_id 56944 --feature_idx 1 --feature_dim 50 --label_idx 0 --label_dim 121 \
  --model graphsage_supervised --mode train`
看下/tmp/log 启动两个，有报错如下
`ZK error when creating root node: bad arguments`

**Comment by yangsiran** [comment]
@baymaxKevin ZK不支持相对路径，需要填写绝对路径，如`/tf_euler`。

**Comment by baymaxKevin** [comment]
改为/data/ljz/tf_euler绝对路径，还是报相同错误
`E0122 16:00:37.517542  7208 zk_server_register.cc:77] ZK error when creating root node: no node.
W0122 16:00:37.517582  7208 graph.h:148] global sampler is not ok
E0122 16:00:37.518566  7208 zk_server_register.cc:99] ZK error when creating meta: no node.
`

**Comment by yangsiran** [comment]
@baymaxKevin 目前euler只会在ZK上创建`/data/ljz/tf_euler`这个节点，麻烦在启动前手动创建`/data/ljz`。

**Comment by baymaxKevin** [comment]
已解决

**Comment by jasonhuxinlei** [comment]
> 已解决

您好，我遇到了和您相同的问题，看到您的解决办法是文件权限问题，我想问您一下具体的解决方法是什么呢，是哪个文件权限不对呢
