### ISSUE TITLE
分布式训练报错-Cannot assign a device for operation att_vec/Initializer/truncated_normal/TruncatedNormal

### ISSUE THREAD

**Issue by wangke1935** [alibaba/euler#82]
InvalidArgumentError (see above for traceback): Cannot assign a device for operation att_vec/Initializer/truncated_normal/TruncatedNormal: Could not satisfy explicit device specification '' because the node node att_vec/Initializer/truncated_normal/TruncatedNormal (defined at /home/euler/tf_euler/python/models/lshne.py:72) having device Device assignments active during op 'att_vec/Initializer/truncated_normal/TruncatedNormal' creation:
  with tf.device(None): </usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py:1501>
  with tf.device(_ReplicaDeviceChooser.device_function</usr/local/lib/python2.7/dist-packages/tensorflow/python/training/device_setter.py, 97>): </home/euler/tf_euler/python/run_loop.py:364>  was colocated with a group of nodes that required incompatible device '/job:ps/task:0'

**Comment by marvelousgirl** [comment]
您好，请问跑通lshne这个模型了吗？
