### ISSUE TITLE
孤立节点

### ISSUE THREAD

**Issue by seafish999** [alibaba/euler#83]
支持孤立节点吗？节点与其他节点没有连接，json中neighbor字段与edge字段都是空。

**Comment by yangsiran** [comment]
@seafish999 支持。

**Comment by seafish999** [comment]
有标签的孤立节点需要放进去学习吗？会对模型效果产生影响吗？

**Comment by seafish999** [comment]
谢谢。 请问有标签的孤立用户需要放到图里吗？对模型有影响吗？
